<div class="topic-block">
    <div class="container-fluid">
        <div class="row">

            <div class="col">
                <div class="row">
                    <div class="topic-header">
                        <h4 class="topic-name"><a href="{% url 'topic' %}">Django testing: Got an error creating the test database: database "database_name" already exists</a></h4>
                    </div>
                </div>

                <div class="row">
                    <div class="topic-stat">
                        <h4 class="topic-users">10 users at topic</h4>
                    </div>
                </div>

                <div class="row">
                    <div class="topic-stat">
                        <h5 class="topic-tags">black-jack, blender</h5>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="topic-element">
                    <h4 class="topic-content">I have a problem with testing. It's my first time writing tests and I have a problem.

                        I just created a test folder inside my app users, and test_urls.py for testing the urls.

                        When I type:

                        python manage.py test users

                        It says:

                        Creating test database for alias 'default'... Got an error creating the test database: database "database_name" already exists

                        Type 'yes' if you would like to try deleting the test database 'database_name', or 'no' to cancel:

                        What does it mean? What happens if I type yes? Do I lose all my data in database?
                    </h4>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="topic-block">
    <div class="container-fluid">
        <div class="row">

            <div class="col">
                <div class="row">
                    <div class="topic-header">
                        <h4 class="topic-name"><a href="{% url 'topic' %}">Not able to connect to Influxdb running in docker container</a></h4>
                    </div>
                </div>

                <div class="row">
                    <div class="topic-stat">
                        <h4 class="topic-users">3 users at topic</h4>
                    </div>
                </div>

                <div class="row-cols-auto">
                    <div class="topic-stat">
                        <h5 class="topic-tags">docker</h5>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="topic-element">
                    <h4 class="topic-content">
I am new to Docker and Influxdb I am trying to setup influxdb database for my project and I added influxdb container in my docker but when I try to connect to database using the command <#influx> it always shows following message

root@0e36c4d4a53f:/# influx Influx Client

Usage: influx [command]

Available Commands:xxxxxxx

Flags: -h, --help Help for the influx command

Use "influx [command] --help" for more information about a command.

I am supposed to get "Connected to http://localhost:8086 version 1.7.7 InfluxDB shell version: 1.7.7".

can someone tell what I am doing wrong here.
                    </h4>
                </div>
            </div>

        </div>
    </div>
</div>